---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin_nvidia
# description will be included in the image's metadata
description: This is a nVidia custom image that includes 1Password to work with Brave, Firefox, Chrome, and Edge. And others such as Twingate.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia-open
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://packages.microsoft.com/fedora/42/prod/config.repo
      - https://packages.microsoft.com/yumrepos/edge/config.repo
      - packages.twingate.com_rpm_.repo
    optfix:
      - brave.com
      - microsoft
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      - https://packages.microsoft.com/keys/microsoft-2025.asc
    install:
      - brave-browser
      - epiphany
      - https://github.com/GoXLR-on-Linux/goxlr-utility/releases/download/v1.2.2/goxlr-utility-1.2.2-1.x86_64.rpm
      - microsoft-edge-stable
      - microsoft-edge-beta
      - packages-microsoft-prod
      - twingate
      - chromium
      - dotnet-sdk-9.0
      - nethogs

  - type: bling
    install:
      - 1password

  - type: script
    snippets:
      - "dotnet tool install --global PowerShell"

  - type: gnome-extensions
    install:
      - Astra Monitor
      - Tiling Shell

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
